# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/gpt-utils',
                'doc_host': 'https://andryramorasata.github.io',
                'git_url': 'https://github.com/andryramorasata/gpt-utils',
                'lib_path': 'gpt_utils'},
  'syms': {'gpt_utils.core': {'gpt_utils.core.foo': ('core.html#foo', 'gpt_utils/core.py')}}}